<?xml version="1.0"?>

<robot name="scout_v2" 
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="robot_namespace" default="/" />
    <xacro:arg name="urdf_extras" default="empty.urdf" />

    <xacro:include filename="$(find scout_description)/urdf/scout_wheel_type1.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_wheel_type2.xacro" />

    <xacro:include filename="$(find zed_description)/urdf/zed2i.urdf.xacro" />


    <xacro:property name="M_PI" value="3.14159"/>

    <xacro:property name="base_x_size" value="0.9250000" />
    <xacro:property name="base_y_size" value="0.380000" />
    <xacro:property name="base_z_size" value="0.210000" />

    <xacro:property name="wheelbase" value="0.498" />
    <xacro:property name="track" value="0.58306" />
    <xacro:property name="wheel_vertical_offset" value="-0.0702" />

    <xacro:property name="wheel_length" value="1.1653e-01" />
    <xacro:property name="wheel_radius" value="1.6459e-01" />
    <xacro:macro name="generic_lidar" params="prefix parent_link *origin_block">

      <link name="${prefix}_lidar_link">
        <!-- Görsel: kendi RP LiDAR mesh'in -->
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <mesh filename="file://$(find scout_description)/meshes/rplidar.stl"
                  scale="0.001 0.001 0.001"/>
          </geometry>
        </visual>

        <!-- Çarpışma: basit silindir bırakalım, simülasyonu hafif tutar -->
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="0.05" length="0.04"/>
          </geometry>
        </collision>
      </link>

      <joint name="${prefix}_lidar_joint" type="fixed">
        <parent link="${parent_link}"/>
        <child link="${prefix}_lidar_link"/>
        <xacro:insert_block name="origin_block" />
      </joint>

      <gazebo reference="${prefix}_lidar_link">
        <sensor type="ray" name="${prefix}_lidar_sensor">
          <pose>0 0 0 0 0 0</pose>
          <visualize>true</visualize>
          <update_rate>10</update_rate>

          <ray>
            <scan>
              <horizontal>
                <!-- 180° FOV, 0.33° çözünürlük ≈ 546 örnek -->
                <samples>546</samples>
                <resolution>1</resolution>
                <min_angle>-1.570796</min_angle>
                <max_angle>1.570796</max_angle>
              </horizontal>
            </scan>
            <range>
              <min>0.10</min>
              <max>15.0</max>
              <resolution>0.01</resolution>
            </range>
          </ray>

          <plugin name="gazebo_ros_ray_sensor" filename="libgazebo_ros_ray_sensor.so">
            <ros>
              <namespace>/</namespace>
              <output_type>sensor_msgs/LaserScan</output_type>
              <topic>${prefix}_scan</topic>
              <frame_name>${prefix}_lidar_link</frame_name>
            </ros>
          </plugin>
        </sensor>
      </gazebo>
    </xacro:macro>


    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find scout_description)/meshes/base_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0.008" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
            </geometry>
        </collision>
        <collision>
            <origin xyz="0 0 ${base_z_size/6}" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size/6} ${base_y_size*1.65} ${base_z_size/3}"/>
            </geometry>
        </collision>
    </link>

    <link name="inertial_link">
        <inertial>
            <mass value="50" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>
    </link>
    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <joint name="zed_kamera_joint" type="fixed">
      <parent link="base_link"/>
      <child link="zed2i_camera_center"/>
      <origin xyz="0.40 0 0.15" rpy="0 0 0"/> 
    </joint>

    <xacro:zed2i_camera prefix="" />

    <xacro:generic_lidar prefix="front" parent_link="base_link">
      <origin xyz="0.40 0 0.10" rpy="0 0 0"/> 
    </xacro:generic_lidar>

    <xacro:generic_lidar prefix="rear" parent_link="base_link">
      <origin xyz="-0.40 0 0.10" rpy="0 0 ${M_PI}"/> 
    </xacro:generic_lidar>


    <xacro:scout_wheel_type1 wheel_prefix="front_right">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
    </xacro:scout_wheel_type1>
    <xacro:scout_wheel_type2 wheel_prefix="front_left">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:scout_wheel_type2>

    <xacro:scout_wheel_type2 wheel_prefix="rear_left">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:scout_wheel_type2>

    <xacro:scout_wheel_type1 wheel_prefix="rear_right">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
    </xacro:scout_wheel_type1>

    <xacro:include filename="$(arg urdf_extras)" />

    <xacro:include filename="$(find scout_description)/urdf/scout_v2.gazebo" />
</robot>